name: Release

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: '.exe'

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - run: cargo build --release --target ${{ matrix.target }}
      
      - run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/parch${{ matrix.ext }} dist/parch${{ matrix.ext }}
        shell: bash
      
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/parch${{ matrix.ext }}
