name: Release
on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, name: parch, binary: parch }
          - { target: x86_64-pc-windows-msvc, os: windows-latest, name: parch.exe, binary: parch.exe }

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y upx gcc-mingw-w64-x86-64
      - if: matrix.os == 'windows-latest'
        run: choco install upx -y
      - run: cargo build --release --target ${{ matrix.target }}
      - if: matrix.os == 'ubuntu-latest'
        run: upx --best --lzma target/${{ matrix.target }}/release/${{ matrix.binary }} || true
      - if: matrix.os == 'windows-latest'
        run: upx --best --lzma target\\${{ matrix.target }}\\release\\${{ matrix.binary }} || exit 0
      - run: mkdir -p artifacts && (cp target/${{ matrix.target }}/release/${{ matrix.binary }} artifacts/${{ matrix.name }} 2>/dev/null || powershell -Command "New-Item -ItemType Directory -Force artifacts; Copy-Item -Path target\\${{ matrix.target }}\\release\\${{ matrix.binary }} -Destination artifacts\\${{ matrix.name }}")
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: artifacts/${{ matrix.name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: artifacts/*
